# Generated by Django 6.0.6 on 2026-06-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField(verbose_name='Descrizione')),
                ('published', models.BooleanField(default=False, verbose_name='Pubblicato')),
                ('type', models.CharField(choices=[('1', 'Personali'), ('2', 'Collettive')], max_length=1, verbose_name='Tipologia')),
                ('beginning', models.DateField(verbose_name='Data di inizio')),
            ],
            options={
                'verbose_name': 'mostra',
                'verbose_name_plural': 'mostre',
                'ordering': ['-beginning'],
            },
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titolo')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('pubdate', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Data ultima modifica')),
                ('published', models.BooleanField(default=True, verbose_name='Pubblicato')),
                ('content', models.TextField(blank=True, verbose_name='Descrizione')),
                ('image', models.ImageField(upload_to='opere', verbose_name='Immagine')),
                ('thumb', models.ImageField(upload_to='opere_thumb', verbose_name='Miniatura')),
                ('creation_year', models.CharField(max_length=4, verbose_name='Anno')),
                ('typology', models.CharField(choices=[('S', 'Sculture'), ('G', 'Gioielli'), ('D', 'Disegni')], default='S', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Opere',
                'ordering': ['-creation_year', 'title'],
            },
        ),
    ]
