# Generated by Django 6.0.6 on 2026-06-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opere', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opera',
            options={'ordering': ['display_order', 'pk'], 'verbose_name_plural': 'Opere'},
        ),
        migrations.AddField(
            model_name='opera',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Ordine'),
        ),
    ]
