# Generated by Django 6.0.6 on 2026-06-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opere', '0002_add_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mostra',
            options={'ordering': ['display_order'], 'verbose_name': 'mostra', 'verbose_name_plural': 'mostre'},
        ),
        migrations.AddField(
            model_name='mostra',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Ordine'),
        ),
    ]
